### ISSUE TITLE
自动基建1.5.4

### ISSUE THREAD

**Issue by tangkent2** [UnrealMultiple/TShockPlugin#351]
监狱只建了宝箱没建监狱

**Comment by ACaiCat** [comment]
提供复现方法

**Comment by tangkent2** [comment]
更新插件然后把新的地图装上去，然后开启服务器，自动建好后进服后就发现只建了宝箱，没建监狱

**Comment by 1242509682** [comment]
> 更新插件然后把新的地图装上去，然后开启服务器，自动建好后进服后就发现只建了宝箱，没建监狱

请问是什么地图种子，地图大小，是否含有十周年或者颠倒特性，地图的出生点是否在海边亦或者是自己做得地图。
