### ISSUE TITLE
where should I place the md and pdb files

### ISSUE THREAD

**Issue by Hexagonforce12** [UnrealMultiple/TShockPlugin#407]
![IMG_20240819_040252](https://github.com/user-attachments/assets/16931992-cbf3-4582-beb5-c1999d61a837)
all plugins always have additional files, md and pdb files, usually only dll files

**Comment by sgkoishi** [comment]
They are unnecessary and you can safely just delete them:
* md is some kind of text (e.g. readme)
* pdb contains some troubleshooting info (for the developer/author) when something goes wrong

**Comment by Hexagonforce12** [comment]
Oh ok
