### ISSUE TITLE
please update the disable godmode plugin,This plugin is good for anti-cheat but The plugin doesn't work very well

### ISSUE THREAD

**Issue by Hexagonforce12** [UnrealMultiple/TShockPlugin#409]

**Comment by Controllerdestiny** [comment]
Which plugin are you referring to, please tell us the name of the plugin.

**Comment by sgkoishi** [comment]
You need to provide more info to help troubleshoot what's going wrong, e.g. record a video. Alternatively, you can just delete this plugin 😉

**Comment by Hexagonforce12** [comment]
DisableGodMod plugin, the plugin can detect godmode invicible, but sometimes it doesn't work

**Comment by sgkoishi** [comment]
You need to provide more info. Does it crash? Does it kick innocent players? What did the players do before they got kicked?

* There _will_ be eventually false positives and false negatives due to how Terraria works. In addition, this plugin is poorly designed and much more likely to broken detection. You should write your own plugin if it doesn't fit your needs.

**Comment by Controllerdestiny** [comment]
> DisableGodMod plugin, the plugin can detect godmode invicible, but sometimes it doesn't work

hi bro I think this plugin is failure，he will attack from time to time to deal damage to the player，This may cause the player invincibility buff to fail，I don't recommend use it，I willremove it in the future。

**Comment by Hexagonforce12** [comment]
This plugin already works, I tried it when I activated godmode, but this plugin takes a very long time to detect it, I hope it can be detected faster

**Comment by sgkoishi** [comment]
I have no idea what you mean by “faster” when you said it already kicks immediately.
Again, the plugin is based on a **ridiculous** idea and you should **just delete it**.

**Comment by Hexagonforce12** [comment]
This plugin is good bro for anti-cheat like godmode,Even though it doesn't work that much
