### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by Hexagonforce12** [UnrealMultiple/TShockPlugin#432]
### 已阅须知

- [X] 是

### 功能有益

- [X] 是

### 插件名字

Challenger

### 需要什么功能?

控制台出现错误，但插件仍然有效
![IMG_20240830_214501](https://github.com/user-attachments/assets/737eb3fc-04d1-4012-93ac-7b29d5bb7565)

**Comment by ACaiCat** [comment]
Fix #433
