### ISSUE TITLE
[BUG] Economic.skill AI样式部分，攻击间隔的功能无法正常生效

### ISSUE THREAD

**Issue by TKFTshaobing** [UnrealMultiple/TShockPlugin#456]
### 已阅须知

- [X] 是

### BUG可复现

- [X] 是

### 插件最新

- [X] 是

### 插件名字

Economic.skill

### 系统

Linux

### 发生了什么?

AI样式部分，攻击间隔的功能无法正常生效，之前可以，单位为帧，现在无论填多少都是1帧间隔(应该)

### 如何复现

1.弹幕AI样式选1/0
2.下面AI样式部分填好发射的子弹幕，射速，攻击范围
3.攻击间隔随便填一个数

### 期望的结果?

修复bug

**Comment by Controllerdestiny** [comment]
鼠鼠没给你解决吗

**Comment by Controllerdestiny** [comment]
经测试它是有效的，能否进一步检查是否与其他插件存在冲突？

**Comment by Controllerdestiny** [comment]
没后续关了可以重新打开
