### ISSUE TITLE
Yo, why isn't the plugin list displayed anymore? it is very important to look at the plugin information

### ISSUE THREAD

**Issue by Hexagonforce12** [UnrealMultiple/TShockPlugin#461]
### 已阅须知 | Read the guidelines

- [X] 是 | Yes

### 功能有益 | Feature is beneficial

- [X] 是 | Yes

### 插件名字 | Plugin Name

?

### 需要什么功能? | What feature do you need?

Please restore the plugin list display as before

**Comment by sgkoishi** [comment]
There is. All you need is to click the tiny triangle to see the details.

**Comment by THEXN** [comment]
![Screenshot_2024-09-10-00-48-17-560_mark via](https://github.com/user-attachments/assets/f51a33a3-758e-499d-be58-d8b085f0cb6c)
？

**Comment by Hexagonforce12** [comment]
oh sorry I didn't see it, because I opened the github site on phone
