### ISSUE TITLE
how to use English translation on the challenger plugin

### ISSUE THREAD

**Issue by Hexagonforce12** [UnrealMultiple/TShockPlugin#463]
### 已阅须知 | Read the guidelines

- [X] 是 | Yes

### 功能有益 | Feature is beneficial

- [X] 是 | Yes

### 插件名字 | Plugin Name

Challenger

### 需要什么功能? | What feature do you need?

I saw that the changelog added English translation, how to use it

**Comment by sgkoishi** [comment]
Oh right, I forgot to add them to the list. You don't need to do anything to use it - it will be English if your server is English.

**Comment by Hexagonforce12** [comment]
If have translated template.pot then how do install it in the plugin?

**Comment by sgkoishi** [comment]
I would suggest submitting it to the repo and the pipeline will build the version with translation inside automatically. Otherwise, you need to build the plugin yourself.

**Comment by Hexagonforce12** [comment]
Damn bro, I don't have a PC to build plugins,i just use phone

**Comment by Controllerdestiny** [comment]
你可以对文本进行翻译，然后在github上提交给我们，在pot文件中
