### ISSUE TITLE
[BUG] ec.plus强化clear的bug

### ISSUE THREAD

**Issue by 1653638943** [UnrealMultiple/TShockPlugin#479]
### 已阅须知 | Read the guidelines

- [X] 是 | Yes

### BUG可复现 | Bug is reproducible

- [X] 是 | Yes

### 插件最新 | Plugin is up-to-date

- [X] 是 | Yes

### 插件名字 | Plugin Name

ec.plus

### 系统 | System

Windows

### 发生了什么? | What happened?

玩家强化完武器后，clear强化，然后退出服务器重进，强化还在，然后经验返还的也在！

### 如何复现 | How to reproduce

武器plus强化

plus clear清除，返还经验

退出游戏，重新进

plus武器强化依旧存在，而且返还的经验也存在

### 期望的结果? | Expected result?

解决bug

### 文本日志 | Text log

```shell
无
```

### 控制台日志 | Console log

```shell
无
```

**Comment by Controllerdestiny** [comment]
#481 可以在Action下载测试一下
