### ISSUE TITLE
Please fix the problem if opening the chest

### ISSUE THREAD

**Issue by Hexagonforce12** [UnrealMultiple/TShockPlugin#486]
### 已阅须知 | Read the guidelines

- [X] 是 | Yes

### 功能有益 | Feature is beneficial

- [X] 是 | Yes

### 插件名字 | Plugin Name

PerPlayerLoot

### 需要什么功能? | What feature do you need?

If have used this plugin and have progressed quite far, if  open a world chest it is usually very delayed and takes a long time to open it, please fix it so that there is no delay when opening the world chest

**Comment by THEXN** [comment]
This plugin issue is quite significant, and it is likely to be removed from the repository (even fixing it would require considerable effort). You can use a similar plugin called CaiRewardChest, which also achieves the goal of providing each player with an initial set of resources from a chest.

**Comment by sgkoishi** [comment]
ez fix https://github.com/UnrealMultiple/TShockPlugin/blob/f5fdcab2d7e2124c1618991b023e0584a3fc7608/src/PerPlayerLoot/FakeChestDatabase.cs#L248 https://github.com/UnrealMultiple/TShockPlugin/blob/f5fdcab2d7e2124c1618991b023e0584a3fc7608/src/PerPlayerLoot/FakeChestDatabase.cs#L161 https://github.com/UnrealMultiple/TShockPlugin/blob/f5fdcab2d7e2124c1618991b023e0584a3fc7608/src/PerPlayerLoot/FakeChestDatabase.cs#L166

**Comment by Hexagonforce12** [comment]
Compile it to dll file
