### ISSUE TITLE
[BUG] About Team 的备注不明确，很容易误导（还有就是输入后变成另一个了）

### ISSUE THREAD

**Issue by delanq** [UnrealMultiple/TShockPlugin#493]
### 已阅须知 | Read the guidelines

- [X] 是 | Yes

### BUG可复现 | Bug is reproducible

- [X] 是 | Yes

### 插件最新 | Plugin is up-to-date

- [X] 是 | Yes

### 插件名字 | Plugin Name

About Team

### 系统 | System

Windows

### 发生了什么? | What happened?

About Team 的备注不明确，很容易误导（还有就是输入后变成另一个了）

### 如何复现 | How to reproduce

没有

### 期望的结果? | Expected result?

写明该如何编写配置

### 文本日志 | Text log

```shell
原默认
{
  "开启插件": true,
  "组的队伍": {
    "组名字/groupname": "队伍名称teamname中文或English",
    "default": "red",
    "某个组": "红队"
  }
}
用下面的覆盖
{
  "开启插件": true,
  "组的队伍": {
    "guest": "蓝队",
    "default": "red",
    "owner": "红队"
  }
}
变为
{
  "开启插件": true,
  "组的队伍": {
    "组名字/groupname": "队伍名称teamname中文或English",
    "default": "red",
    "某个组": "红队",
    "guest": "蓝队",
    "owner": "红队"
  }
}
```

### 控制台日志 | Console log

```shell
没有
```

**Comment by ACaiCat** [comment]
没看懂

**Comment by ACaiCat** [comment]
哦，也行这个是BUG
