### ISSUE TITLE
[建议|Suggestion] 技能的一些有意思的建议

### ISSUE THREAD

**Issue by 11xyao** [UnrealMultiple/TShockPlugin#506]
### 已阅须知 | Read the guidelines

- [X] 是 | Yes

### 功能有益 | Feature is beneficial

- [X] 是 | Yes

### 插件名字 | Plugin Name

skill

### 需要什么功能? | What feature do you need?

1.技能概率触发
2.增加触发以后有一个持续时间，比如我触发了技能，让其10s内只要  打击（触发方式）敌怪能治愈/回蓝/拉怪...然后再进入CD
3.以弹幕为基础，这个功能在gk的自定义套装上有，使用武器比如手枪的子弹打中敌怪就能在打中的那个位置生成弹幕，近战剑打中也有，很神奇所以来提一嘴

**Comment by Controllerdestiny** [comment]
#468
