### ISSUE TITLE
[BUG] VeinMiner满背包时可刷奖励

### ISSUE THREAD

**Issue by CongealEK** [UnrealMultiple/TShockPlugin#510]
### 已阅须知 | Read the guidelines

- [X] 是 | Yes

### BUG可复现 | Bug is reproducible

- [X] 是 | Yes

### 插件最新 | Plugin is up-to-date

- [X] 是 | Yes

### 插件名字 | Plugin Name

VeinMiner

### 系统 | System

Windows

### 发生了什么? | What happened?

背包满的时候去挖达到可获得奖励数量的矿，只会挖掉一个矿，但却会给予一个奖励物品，然后就可以用这个刷奖励

### 如何复现 | How to reproduce

这个连锁挖矿有个bug，背包满的时候去挖达到可获得奖励数量的矿即可（要开启奖励机制）

### 期望的结果? | Expected result?

修复

**Comment by ACaiCat** [comment]
MayBe需要重新生成配置文件
