### ISSUE TITLE
[建议|Suggestion] 将json配置中的key名从中文改为英文

### ISSUE THREAD

**Issue by serverbread-DEV** [UnrealMultiple/TShockPlugin#514]
### 已阅须知 | Read the guidelines

- [X] 是 | Yes

### 功能有益 | Feature is beneficial

- [X] 是 | Yes

### 插件名字 | Plugin Name

大部分json key名为 中文的插件

### 需要什么功能? | What feature do you need?

rt，应该将json配置中的key名从中文改为英文。

因为某些情景下中文字符可能无法正常显示（如在linux的tty下会将中文显示为方框）。

况且中文更容易出现乱码的情况。

**Comment by ACaiCat** [comment]
确实是这样的，不过改掉之后会导致配置文件失效,(Maybe需要写配置文件转换), 所以目前大概是能不改就不改，或者逐步改，配置大的插件估计不会改(改完覆盖了服主就红温了)

**Comment by serverbread-DEV** [comment]
> 确实是这样的，不过改掉之后会导致配置文件失效,(Maybe需要写配置文件转换), 所以目前大概是能不改就不改，或者逐步改，配置大的插件估计不会改(改完覆盖了服主就红温了)

直接升级配置文件应该是可行的方案。

但是更新后的配置文件腐竹还能看懂吗？
我认为可以写到`README`里解释各配置项或者直接换用其他支持注释的配置文件（如`json5`、`yaml`、etc.）。
但这样又有些不妥？

总之这个迁移过程应该是有些痛苦的（X

但最好还是改一下。

**Comment by Controllerdestiny** [comment]
> > 确实是这样的，不过改掉之后会导致配置文件失效,(Maybe需要写配置文件转换), 所以目前大概是能不改就不改，或者逐步改，配置大的插件估计不会改(改完覆盖了服主就红温了)
> 
> 直接升级配置文件应该是可行的方案。
> 
> 但是更新后的配置文件腐竹还能看懂吗？ 我认为可以写到`README`里解释各配置项或者直接换用其他支持注释的配置文件（如`json5`、`yaml`、etc.）。 但这样又有些不妥？
> 
> 总之这个迁移过程应该是有些痛苦的（X
> 
> 但最好还是改一下。

Newtosoto.json其实支持注释的，也许我们应该仓库插件的将Config标准化。

**Comment by ACaiCat** [comment]
Mybe大概是:
- [ ] JSON改TOML
- [ ] KEY去中文
- [ ] TOML库还没定.jpg

**Comment by LaoSparrow** [comment]
https://stackoverflow.com/questions/33155458/json-deserialize-from-legacy-property-names
建议这种解决方法如何，加一个 LegacyJsonPropertyNames Attribute
到时候做config 规范化的时候一起给这东西加上

**Comment by Controllerdestiny** [comment]
> https://stackoverflow.com/questions/33155458/json-deserialize-from-legacy-property-names 建议这种解决方法如何，加一个 LegacyJsonPropertyNames Attribute 到时候做配置 规范化的时候一起给这东西加上

似乎没完全解决现在的窘境
