### ISSUE TITLE
关于Economic的建议

### ISSUE THREAD

**Issue by TKFTshaobing** [UnrealMultiple/TShockPlugin#521]
### 已阅须知 | Read the guidelines

- [X] 是 | Yes

### 功能有益 | Feature is beneficial

- [X] 是 | Yes

### 插件名字 | Plugin Name

Economic套件

### 需要什么功能? | What feature do you need?

~~把Economic.Skill的AI样式2效果加入Economic.projects~~

2.Economic.Skill加个skill give的指令(搭配Economic.RPG做到升级获取技能)
3.Economic.Skill能否加个新的技能类型，想象中的大概效果为：
(1)独立于主动与被动技能，不会占用被动与主动技能的栏位
(2)只能通过指令获得/删除，而不是通过skill buy/del获得/删除，可以搭配Economic.RPG的执行指令功能实现某个级别时获得这种技能，做到类似某个等级时学习的新的天赋这种

**Comment by Controllerdestiny** [comment]
ec.proj 的AI样式目前没有添加的打算
