### ISSUE TITLE
[BUG] LifemaxExtra 提升生命值上限没有效果

### ISSUE THREAD

**Issue by airdm** [UnrealMultiple/TShockPlugin#525]
### 已阅须知 | Read the guidelines

- [X] 是 | Yes

### BUG可复现 | Bug is reproducible

- [X] 是 | Yes

### 插件最新 | Plugin is up-to-date

- [X] 是 | Yes

### 插件名字 | Plugin Name

LifemaxExtra

### 系统 | System

Windows

### 发生了什么? | What happened?

LifemaxExtra 提升生命值上限没有效果

### 如何复现 | How to reproduce

配置文件中的上限无效果,单独用/hp设置用户上限也无效果.

### 期望的结果? | Expected result?

希望可以正常使用

**Comment by Controllerdestiny** [comment]
是否检查了config.json中设置的生命值上限

**Comment by airdm** [comment]
> 是否检查了config.json中设置的生命值上限

设置了    
"MaxHP": 1000,
"MaxMP": 400,
需要删掉这两个配置吗?

**Comment by THEXN** [comment]
是不是没开ssc啊
