### ISSUE TITLE
[建议|Suggestion] add English Readme for Economics series plugins

### ISSUE THREAD

**Issue by Hexagonforce12** [UnrealMultiple/TShockPlugin#530]
### 已阅须知 | Read the guidelines

- [X] 是 | Yes

### 功能有益 | Feature is beneficial

- [X] 是 | Yes

### 插件名字 | Plugin Name

Economic

### 需要什么功能? | What feature do you need?

Add English Readme for all economic readme

**Comment by ItzMelton** [comment]
they are trying to, you don't have to ask since they already know.

**Comment by Hexagonforce12** [comment]
yes
