### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Hexagonforce12** [UnrealMultiple/TShockPlugin#532]
### 已阅须知 | Read the guidelines

- [X] 是 | Yes

### BUG可复现 | Bug is reproducible

- [X] 是 | Yes

### 插件最新 | Plugin is up-to-date

- [X] 是 | Yes

### 插件名字 | Plugin Name

AutoPluginManager

### 系统 | System

手机 | Mobile

### 发生了什么? | What happened?

the autopluginmanager plugin when running the /apm l command in the game causes the server to delay and lag badly

**Comment by ItzMelton** [comment]
I tried the plugin on my mobile and it doesn't lag, is it your server or phone issue?
try using a pc if it still lags then i might try fixing it

**Comment by Hexagonforce12** [comment]
> I tried the plugin on my mobile and it doesn't lag, is it your server or phone issue? try using a pc if it still lags then i might try fixing it (Recommend speaking in chinese)

This isn't a device issue, but it's the plugin that has a bug, just try it yourself

**Comment by Hexagonforce12** [comment]
try the new version of the plugin

**Comment by THEXN** [comment]
May I ask if you have used 'Use Github source': true, in the AutoPluginManager.json?And I feel that this phenomenon might be normal. When using the /apm u and /apm i commands, it will download and unzip the plugin packages, which would occupy network bandwidth. It seems that experiencing some lag at this time is normal. Or are you also experiencing lag when using other apm commands?

**Comment by sgkoishi** [comment]
I would assume there's some kind of networking issue with your server which have limited access to Chinese websites.

**Comment by Hexagonforce12** [comment]
Previously I used the old plugin and it didn't cause delay and lag when using the command /apm l in the game not on the console, but after I used the new version of the plugin it caused delay and lag if use /apm l command in game

**Comment by Hexagonforce12** [comment]
> May I ask if you have used 'Use Github source': true, in the AutoPluginManager.json?And I feel that this phenomenon might be normal. When using the /apm u and /apm i commands, it will download and unzip the plugin packages, which would occupy network bandwidth. It seems that experiencing some lag at this time is normal. Or are you also experiencing lag when using other apm commands?

![IMG_20241025_110542](https://github.com/user-attachments/assets/6e138726-d494-452f-9ef9-ddaa5edb66f4)
wtf, apparently I haven't set use github source to true😅, I thought it was true because previously I was using an old version of the plugin and that was when I installed the plugin and it was automatically true,But the new version is actually false😅

**Comment by THEXN** [comment]
> > 请问您是否在AutoPluginManager.json中使用了“使用 Github 源代码”：true？我觉得这种现象可能是正常的。使用 /apm u 和 /apm i 命令时，会下载并解压插件包，会占用网络带宽。此时出现一些滞后似乎是正常的。或者您在使用其他 apm 命令时也遇到延迟？
> 
> ![IMG_20241025_110542](https://private-user-images.githubusercontent.com/109804725/379998125-6e138726-d494-452f-9ef9-ddaa5edb66f4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4MjY2MjksIm5iZiI6MTcyOTgyNjMyOSwicGF0aCI6Ii8xMDk4MDQ3MjUvMzc5OTk4MTI1LTZlMTM4NzI2LWQ0OTQtNDUyZi05ZWY5LWRkYWE1ZWRiNjZmNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQwMzE4NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOTZjN2MxOWI5MzZmYTU2M2Y1ODU3YjFiZTdjNzM2MGRkZWMyZTY5MzJkMDY0MWRjM2YwNjI3YzhjOTU3NTVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.o3v87EPJ3tL9liBZpgMDJPk1Wh2S7KsA-hT_K5bR800)wtf，显然我没有把使用 github source 设置为 true😅，我以为是真的，因为之前我用的是旧版本的插件，那是我安装插件的时候自动为 true，但是新版本其实是 false😅，抱歉

So, has there been any improvement after switching to GitHub?

**Comment by Hexagonforce12** [comment]
> > > 请问您是否在AutoPluginManager.json中使用了“使用 Github 源代码”：true？我觉得这种现象可能是正常的。使用 /apm u 和 /apm i 命令时，会下载并解压插件包，会占用网络带宽。此时出现一些滞后似乎是正常的。或者您在使用其他 apm 命令时也遇到延迟？
> > 
> > 
> > ![IMG_20241025_110542](https://private-user-images.githubusercontent.com/109804725/379998125-6e138726-d494-452f-9ef9-ddaa5edb66f4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4MjY2MjksIm5iZiI6MTcyOTgyNjMyOSwicGF0aCI6Ii8xMDk4MDQ3MjUvMzc5OTk4MTI1LTZlMTM4NzI2LWQ0OTQtNDUyZi05ZWY5LWRkYWE1ZWRiNjZmNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQwMzE4NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOTZjN2MxOWI5MzZmYTU2M2Y1ODU3YjFiZTdjNzM2MGRkZWMyZTY5MzJkMDY0MWRjM2YwNjI3YzhjOTU3NTVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.o3v87EPJ3tL9liBZpgMDJPk1Wh2S7KsA-hT_K5bR800)wtf，显然我没有把使用 github source 设置为 true😅，我以为是真的，因为之前我用的是旧版本的插件，那是我安装插件的时候自动为 true，但是新版本其实是 false😅，抱歉
> 
> So, has there been any improvement after switching to GitHub?

Yess
