### ISSUE TITLE
[建议|Suggestion] [Economics] more features from SEconomy & querying own or others amount & currency leaderboard

### ISSUE THREAD

**Issue by Hexagonforce12** [UnrealMultiple/TShockPlugin#534]
### 已阅须知 | Read the guidelines

- [X] 是 | Yes

### 功能有益 | Feature is beneficial

- [X] 是 | Yes

### 插件名字 | Plugin Name

EconomicsAPI

### 需要什么功能? | What feature do you need?

I still don't see much of the EconomicsAPI plugin system, please add more features like that SEconomy plugin:https://github.com/Maxthegreat99/SEconomy
And there is no command to see our own or other people's currency,So add a command to view currency such as /my bank, /view bank <player>, /bank leaderboard
SEconomy plugin screnshot:
![Screenshot_2024-10-25-10-42-46-59](https://github.com/user-attachments/assets/e2525e93-4c9d-4b01-947a-b567a43b4cea)
![Screenshot_2024-10-25-10-42-25-56](https://github.com/user-attachments/assets/e51070a3-d224-4430-b15a-55069b5ec883)

**Comment by sgkoishi** [comment]
What features from SEconomy are important to you? These 'economy' plugins are mainly used as XP instead of a real bank so people don't check their or others' currency - and the status text shows their XP automatically.

**Comment by Hexagonforce12** [comment]
Seeing the currency is also important,Because most economic plugins make a lot of purchases such as upgrading, buying items in shops and so on, we have to know how much our currency is and see what the currency price is for upgrading Or buy something So as not to be curious,Features that might be good for the SEconomy plugin to add include setting the name of the currency that appears when killing an enemy so that not numbers but names appear,As well as commands to view other currency and  people currency, and the currency leaderboard

**Comment by LaoSparrow** [comment]
after this pr is merged,
you can use `/bank query` to query your own amount
or use `/bank query <player_name>` to query other player's amount.

However, I don't really see the necessity to implement the leaderboard feature, as the currencies in Economics series plugins are most likely a kind of xp which would be consumed when upgrading a player's own rank and group.
Maybe need to implement it in a dedicated plugin? But definitely not in EconomicsAPI.

**Comment by Hexagonforce12** [comment]
> after this pr is merged, you can use `/bank query` to query your own amount or use `/bank query <player_name>` to query other player's amount.
> 
> However, I don't really see the necessity to implement the leaderboard feature, as the currencies in Economics series plugins are most likely a kind of xp which would be consumed when upgrading a player's own rank and group. Maybe need to implement it in a dedicated plugin? But definitely not in EconomicsAPI.

Ok,Thanks for updating
