### ISSUE TITLE
[建议|Suggestion] [Economics] need better documentation for config files

### ISSUE THREAD

**Issue by Hexagonforce12** [UnrealMultiple/TShockPlugin#535]
### 已阅须知 | Read the guidelines

- [X] 是 | Yes

### 功能有益 | Feature is beneficial

- [X] 是 | Yes

### 插件名字 | Plugin Name

For all Economics plugins

### 需要什么功能? | What feature do you need?

Please provide a guide or example on how to fill in the data in the "[ ]" which is empty section on all of Economics plugin because there is no guide at all on how to fill in the data there, because maybe that's important too
![IMG_20241025_111326](https://github.com/user-attachments/assets/cd77a8f2-c2c8-47b7-b767-60944b209ae4)
![IMG_20241025_111358](https://github.com/user-attachments/assets/8b287579-cdd3-4d8d-a8e6-7dd3047ba619)

**Comment by sgkoishi** [comment]
All of these are strings except the upgrade reward.

**Comment by Hexagonforce12** [comment]
Yes, but how to fill it in,because there is no guide on how to do it

**Comment by THEXN** [comment]
"进度限制": [
        "克苏鲁之眼"
      ],
      "升级指令": [
        "/permabuff 113",
        "/i 74  1",
        "/i 3206  5"
      ],
      "附加权限": [],
      "升级奖励": [
        {
          "物品ID": 119,
          "数量": 1,
          "前缀": 81
        },
        {
          "物品ID": 1355,
          "数量": 99,
          "前缀": 0
        }
      ],
      
     “进度限制”Indeed, the progress limitations do not provide the corresponding table, and it will be supplemented and updated subsequently.

**Comment by THEXN** [comment]
"附加权限": [
        "weaponplus.plus",
        "tshock.admin"
      ],

**Comment by THEXN** [comment]
“进度限制”：https://github.com/THEXN/TShockPlugin/blob/master/src/EconomicsAPI/Enumerates/ProgressType.cs

**Comment by Hexagonforce12** [comment]
wow thank you all🔥
