### ISSUE TITLE
[BUG] Economic.skill的bug

### ISSUE THREAD

**Issue by TKFTshaobing** [UnrealMultiple/TShockPlugin#541]
### 已阅须知 | Read the guidelines

- [X] 是 | Yes

### BUG可复现 | Bug is reproducible

- [X] 是 | Yes

### 插件最新 | Plugin is up-to-date

- [X] 是 | Yes

### 插件名字 | Plugin Name

Economic.skill

### 系统 | System

Linux

### 发生了什么? | What happened?

配置中的被动技能上限效果失效，反而改购买主动技能最大数量会控制其上限

### 如何复现 | How to reproduce

正常修改配置

### 期望的结果? | Expected result?

修复

**Comment by Controllerdestiny** [comment]
预计下个版本不分主动与被动的技能类型
