### ISSUE TITLE
[BUG] blank mesage 

### ISSUE THREAD

**Issue by pacenadhif777** [UnrealMultiple/TShockPlugin#544]
### 已阅须知 | Read the guidelines

- [X] 是 | Yes

### BUG可复现 | Bug is reproducible

- [X] 是 | Yes

### 插件最新 | Plugin is up-to-date

- [X] 是 | Yes

### 插件名字 | Plugin Name

rainbow chat

### 系统 | System

Windows

### 发生了什么? | What happened?

when type /help only blank message appears

### 如何复现 | How to reproduce

/slap clai

### 期望的结果? | Expected result?

.

**Comment by 1242509682** [comment]
I don't understand what you're saying? If you just want to view the menu of this plugin，Please type: `/rc`
When your server uses it, it has already taken over your character's chat events, and you can only switch between two chat coloring options with this command,but It will not affect the operation of other commands.

**Comment by pacenadhif777** [comment]
> I don't understand what you're saying? If you just want to view the menu of this plugin，Please type: `/rc` When your server uses it, it has already taken over your character's chat events, and you can only switch between two chat coloring options with this command,but It will not affect the operation of other commands.

no when i type /help (to show all comand) only blank message appears
