### ISSUE TITLE
[BUG] +建议Economic

### ISSUE THREAD

**Issue by TKFTshaobing** [UnrealMultiple/TShockPlugin#549]
### 已阅须知 | Read the guidelines

- [X] 是 | Yes

### BUG可复现 | Bug is reproducible

- [X] 是 | Yes

### 插件最新 | Plugin is up-to-date

- [X] 是 | Yes

### 插件名字 | Plugin Name

Economic.skill与Economic.RPG

### 系统 | System

Linux

### 发生了什么? | What happened?

bug：
economic.rpg的rank指令失效
或者rank可以正常使用，但提示需要手持物品，但配置中手持物品处是什么也没填
建议：
economic.skill
建议把主动技能与被动技能上限分开，不然就不能 限制被动技能数量但不限制主动技能数量

### 如何复现 | How to reproduce

正常写配置

### 期望的结果? | Expected result?

修复

### 文本日志 | Text log

```shell
rank失效：
System. ArgumentOutOfRangeResponse：索引超出范围。必须是非负的并且小于收藏的大小。（参数“index”）
   位于System.Collections.Generic.List ' 1.get_Project（Int 32索引
```

**Comment by Controllerdestiny** [comment]
skill设计上不存在被动与主动技能的分别，只存在触发模式的不同。
