### ISSUE TITLE
summon limit

### ISSUE THREAD

**Issue by pacenadhif777** [UnrealMultiple/TShockPlugin#552]
### 已阅须知 | Read the guidelines

- [X] 是 | Yes

### 功能有益 | Feature is beneficial

- [X] 是 | Yes

### 插件名字 | Plugin Name

suggest

### 需要什么功能? | What feature do you need?

有没有插件可以限制弹出的小兵数量？

**Comment by THEXN** [comment]
没懂，什么小兵？召唤物？仆从？

**Comment by 1242509682** [comment]
我的私人仓库里有个[自定义怪物](https://github.com/1242509682/CustomMonster),你可以用这个解决问题，由于它的作者不愿意开源，里面涵盖了很多中文变量不适合发到这个仓库里来。

**Comment by 1242509682** [comment]
在`再匹配`里，添加你需要限制数量的NPCID，在`怪物条件`里修改`符合数`就是限制这些怪物的数量了：
```json
      "标志": "雕像神教",
      "怪物ID": 0,
      "再匹配": [
        46,
        47,
        464,
        168,
        470,
        148,
        149,
        465,
        57,
        55,
        230
      ],
      (省略...)
       "怪物条件": [
          {
            "怪物ID": 0,
            "查标志": "雕像神教",
            "指示物": [],
            "范围内": 0,
            "血量比": 0,
            "符合数": 10
          }
        ]
```
![防止雕像神教](https://github.com/user-attachments/assets/b27f1261-7b1a-4f55-b31d-beb20a4b28af)

**Comment by pacenadhif777** [comment]
> I don't understand. What is a minion? A summon? A servant?

我的意思是添加召唤限制，例如地棱柱和龙杖的限制只能召唤12个小兵

i mean add limiter for minion example: terraprisma, dragon staff etc.

**Comment by sgkoishi** [comment]
https://github.com/moisterrific/SummonLimit

**Comment by Controllerdestiny** [comment]
pr #555 我在ServerTool插件中添加了一个配置"限制召唤物数量"可以实现你的需求，当pr合并后此issue将关闭。
