### ISSUE TITLE
[BUG] godmode plugin

### ISSUE THREAD

**Issue by pacenadhif777** [UnrealMultiple/TShockPlugin#553]
### 已阅须知 | Read the guidelines

- [X] 是 | Yes

### BUG可复现 | Bug is reproducible

- [X] 是 | Yes

### 插件最新 | Plugin is up-to-date

- [X] 是 | Yes

### 插件名字 | Plugin Name

unreal plugin

### 系统 | System

Windows

### 发生了什么? | What happened?

无法检测到健康状况低于 0 的作弊用户，受到伤害，但他们不会死亡，他们的健康状况会降至负值（我希望你明白我在说什么，我正在使用翻译器）

### 如何复现 | How to reproduce

使用作弊

### 期望的结果? | Expected result?

每个人都希望一切顺利所以删除这个选项

### 文本日志 | Text log

```shell
,
```

**Comment by sgkoishi** [comment]
You can use English or whichever language you use. Such detection is kinda useless, might be implemented or maybe not as the use case is quite limited.

**Comment by 1242509682** [comment]
你所描述的问题，可能不是插件本身检测机制BUG，而是客户端数据同步不上。
这个BUG对于很多擅长反作弊的服务器都没有办法。
我倒是有个能针对他的好主意：比如使用这个插件，它具备修改玩家血量上限的指令`/zmodify 玩家名字 lifemax 600`
利用强制修改他血量的方法，这个插件[ZHIPlayerManager](https://github.com/UnrealMultiple/TShockPlugin/tree/master/src/ZHIPlayerManager)还是可以帮到你把作弊者踢出去的。
这个插件本身会缓存作弊者的部分数据，来加快惩罚的时间间隔。

**Comment by Controllerdestiny** [comment]
此插件即将被移除

**Comment by pacenadhif777** [comment]
> Plugin ini akan segera dihapus

dont delete it i use for my server is very useful

**Comment by pacenadhif777** [comment]
> Masalah yang Anda jelaskan mungkin bukan bug dalam mekanisme deteksi plug-in itu sendiri, namun data klien tidak dapat disinkronkan. BUG ini tidak memiliki solusi karena banyak server yang pandai anti-cheat. Saya punya ide bagus untuk menargetkannya: misalnya, gunakan plugin ini, yang memiliki perintah untuk mengubah batas atas volume darah pemain. `/zmodify 玩家名字 lifemax 600` Dengan menggunakan metode mengubah volume darahnya secara paksa, plugin [ZHIPlayerManager](https://github.com/UnrealMultiple/TShockPlugin/tree/master/src/ZHIPlayerManager) ini masih dapat membantu Anda mengusir penipu. Plug-in ini sendiri akan menyimpan beberapa data penipu untuk mempercepat interval hukuman.

There is no problem with the maximum health threshold, it's just that the minimum health threshold is less than 0. For the plugin itself, this feature already has this feature without adding /zmodify for each player (thanks for helping)

**Comment by Controllerdestiny** [comment]
> > Plugin ini akan segera dihapus
> 
> dont delete it i use for my server is very useful

有人在准备新的与DisableGodMod功能类似的插件。

**Comment by 1242509682** [comment]
> > Masalah yang Anda jelaskan mungkin bukan bug dalam mekanisme deteksi plug-in itu sendiri, namun data klien tidak dapat disinkronkan. BUG ini tidak memiliki solusi karena banyak server yang pandai anti-cheat. Saya punya ide bagus untuk menargetkannya: misalnya, gunakan plugin ini, yang memiliki perintah untuk mengubah batas atas volume darah pemain. `/zmodify 玩家名字 lifemax 600` Dengan menggunakan metode mengubah volume darahnya secara paksa, plugin [ZHIPlayerManager](https://github.com/UnrealMultiple/TShockPlugin/tree/master/src/ZHIPlayerManager) ini masih dapat membantu Anda mengusir penipu. Plug-in ini sendiri akan menyimpan beberapa data penipu untuk mempercepat interval hukuman.
> 
> There is no problem with the maximum health threshold, it's just that the minimum health threshold is less than 0. For the plugin itself, this feature already has this feature without adding /zmodify for each player (thanks for helping)

我已经把新的无敌检查插件写出来了，可能还有些bug，所以暂时不会出现在这个仓库里，你可以尝试向我反馈：[无敌检查](https://github.com/1242509682/GodCheck)
