### ISSUE TITLE
[BUG] Server tools

### ISSUE THREAD

**Issue by pacenadhif778** [UnrealMultiple/TShockPlugin#575]
### 已阅须知 | Read the guidelines

- [X] 是 | Yes

### BUG可复现 | Bug is reproducible

- [X] 是 | Yes

### 插件最新 | Plugin is up-to-date

- [X] 是 | Yes

### 插件名字 | Plugin Name

Server tools

### 系统 | System

Windows

### 发生了什么? | What happened?

![Screenshot_20241121-141048](https://github.com/user-attachments/assets/d7c69a11-a6dc-4e65-82a2-a09bbeaca5ad)

I've used the latest version and it's still the same

### 如何复现 | How to reproduce

.

### 期望的结果? | Expected result?

.

### 文本日志 | Text log

```shell
.
```

**Comment by Controllerdestiny** [comment]
我刚才进行了测试，配置文件中 "限制召唤物数量": 5 当我的召唤物超过这个数量被踢出去了。请检查插件版本，最新版本为1.1.7.6，和配置文件是否正确配置

**Comment by THEXN** [comment]
你的版本是否为1.1.7.7

**Comment by pacenadhif777** [comment]
> I just tested it, and the configuration file has "limit the number of summons": 5. When my summons exceed this number, they are kicked out. Please check the plugin version, the latest version is 1.1.7.7, and whether the configuration file is configured correctly.

I'm using the latest version I just downloaded it earlier,

**Comment by Controllerdestiny** [comment]
经测试依然没发现问题

**Comment by ACaiCat** [comment]
Could you send your ServerTools.json?

**Comment by ACaiCat** [comment]
Hmmmm, I tested it and it could work normally.
You can reopen the issue if necessary
