### ISSUE TITLE
[BUG] ServerTool热重载神秘报错

### ISSUE THREAD

**Issue by ACaiCat** [UnrealMultiple/TShockPlugin#590]
### 已阅须知 | Read the guidelines

- [X] 是 | Yes

### BUG可复现 | Bug is reproducible

- [X] 是 | Yes

### 插件最新 | Plugin is up-to-date

- [X] 是 | Yes

### 插件名字 | Plugin Name

ServerTool

### 系统 | System

Windows

### 发生了什么? | What happened?

![image](https://github.com/user-attachments/assets/80a44b93-8bdc-428e-869b-994b193b0729)

### 如何复现 | How to reproduce

使用APM升级ServerTool

### 期望的结果? | Expected result?

不报错

**Comment by Controllerdestiny** [comment]
邪恶的Detuor
