### ISSUE TITLE
drop lock

### ISSUE THREAD

**Issue by pacenadhif777** [UnrealMultiple/TShockPlugin#598]
### 已阅须知 | Read the guidelines

- [X] 是 | Yes

### 功能有益 | Feature is beneficial

- [X] 是 | Yes

### 插件名字 | Plugin Name

prevent drop

### 需要什么功能? | What feature do you need?

can you make a plugin to prevent players who don't have permission from dropping items? the reason I asked for it is that there are players who use inject drop items in large quantities.

**Comment by sgkoishi** [comment]
By default TShock will block item drop when players are being disabled. You can trigger this rule by `RequireLogin`

**Comment by Controllerdestiny** [comment]
如果你有其他的应用场景可以使用PacketStop插件拦截玩家数据包，但这个插件对使用者可能不太友好。
