### ISSUE TITLE
[BUG] 0 hp can play

### ISSUE THREAD

**Issue by pacenadhif777** [UnrealMultiple/TShockPlugin#599]
### 已阅须知 | Read the guidelines

- [X] 是 | Yes

### BUG可复现 | Bug is reproducible

- [X] 是 | Yes

### 插件最新 | Plugin is up-to-date

- [X] 是 | Yes

### 插件名字 | Plugin Name

godcheck

### 系统 | System

Windows

### 发生了什么? | What happened?

when the player hp 0 it is not detected,  only when it is negative, my suggestion is to give a delay of 5 seconds players with 0 hp are still alive,  kick player

### 如何复现 | How to reproduce

.

### 期望的结果? | Expected result?

.

### 文本日志 | Text log

```shell
.
```

### 控制台日志 | Console log

```shell
.
```

**Comment by sgkoishi** [comment]
#553
