### ISSUE TITLE
[BUG] 使用Lazyapi的插件，即使配置文件编写错误，/reload重载也不会报错

### ISSUE THREAD

**Issue by THEXN** [UnrealMultiple/TShockPlugin#613]
### 已阅须知 | Read the guidelines

- [X] 是 | Yes

### BUG可复现 | Bug is reproducible

- [X] 是 | Yes

### 插件最新 | Plugin is up-to-date

- [X] 是 | Yes

### 插件名字 | Plugin Name

Lazyapi

### 系统 | System

Windows

### 发生了什么? | What happened?

使用Lazyapi的插件，即使配置文件编写错误，/reload重载也不会报错

### 如何复现 | How to reproduce

/reload观察即可

### 期望的结果? | Expected result?

/reload后 使用lazyapi的单独成行列，逐个显示是否加载成功，如果失败，显示报错信息

**Comment by LaoSparrow** [comment]
哪个插件
用CaiPacketDebug没法重现

**Comment by LaoSparrow** [comment]
src/AutoTeam/Configuration.cs
src/ModifyWeapons/Configuration.cs
盲猜这两个
