### ISSUE TITLE
[BUG] [ZHIPlayerManager] message text not wrapped properly with GetString

### ISSUE THREAD

**Issue by LaoSparrow** [UnrealMultiple/TShockPlugin#624]
### 已阅须知 | Read the guidelines

- [X] 是 | Yes

### BUG可复现 | Bug is reproducible

- [X] 是 | Yes

### 插件最新 | Plugin is up-to-date

- [X] 是 | Yes

### 插件名字 | Plugin Name

ZHIPlayerManager

### 系统 | System

Windows

### 发生了什么? | What happened?

message text not wrapped properly with GetString

https://github.com/UnrealMultiple/TShockPlugin/blob/a7edb37bce6f8da49616a467058d10d09dd4fba4/src/ZHIPlayerManager/ZHIPM.Initialize.cs#L1732

### 如何复现 | How to reproduce

1

### 期望的结果? | Expected result?

1

**Comment by ACaiCat** [comment]
My Bad （
